export const researchData = [
  {
    id: 14,
    name: "Mega ETH 101",
    description: "The Next OP/ARB?",
    date: "2025-01-09",
    demoLink: "https://x.com/Autosultan_team/status/1877291659488276898",
  },
  {
    id: 13,
    name: "ARIO 101",
    description: "The first domain on AO, but it's not just an simple domain.",
    date: "2025-01-06",
    demoLink: "https://x.com/Autosultan_team/status/1875950696165728413",
  },
  {
    id: 12,
    name: "Mango Network 101",
    description: "40 days until TGE!",
    date: "2025-01-05",
    demoLink: "https://x.com/Autosultan_team/status/1875788734274400726",
  },
  {
    id: 11,
    name: "MEVX 101",
    description: "Profit-making tools for meme coins!",
    date: "2024-01-03",
    demoLink: "https://x.com/Autosultan_team/status/1874981170141958490",
  },
  {
    id: 10,
    name: "DePIN 101",
    description: "Explanation & Tutorial",
    date: "2025-01-01",
    demoLink: "https://x.com/Autosultan_team/status/1874494512451715095",
  },
  {
    id: 9,
    name: "Rise Chain 101",
    description: "First Gigagas Era",
    date: "2024-12-30",
    demoLink: "https://x.com/Autosultan_team/status/1873456488674730232",
  },
  {
    id: 8,
    name: "Octo Wallet 101",
    description: "The next Phantom Wallet?",
    date: "2024-12-23",
    demoLink: "https://x.com/Autosultan_team/status/1871171171598926197",
  },
  {
    id: 7,
    name: "InitVerse 101",
    description: "80% going to TGE? Q1 2025",
    date: "2024-12-23",
    demoLink: "https://x.com/Autosultan_team/status/1870936953929298255",
  },
  {
    id: 6,
    name: "Lens Protocol 101",
    description: "Funding $46M, TGE soon?",
    date: "2024-12-22",
    demoLink: "https://x.com/Autosultan_team/status/1870554405843665285",
  },
  {
    id: 5,
    name: "GoPlus 101",
    description: "The first on-chain security in Web3",
    date: "2024-12-21",
    demoLink: "https://fittrack.example.com",
  },
  {
    id: 4,
    name: "Somnia Network 101",
    description: "The next Vana? Don't skip it!",
    date: "2024-12-20",
    demoLink: "https://x.com/Autosultan_team/status/1869793522699927666",
  },
  {
    id: 3,
    name: "Hyperliquid 101",
    description: "A newcomer that amazes",
    date: "2024-12-18",
    demoLink: "https://x.com/Autosultan_team/status/1869071465402016099",
  },
  {
    id: 2,
    name: "Airdrop Learn 101",
    description: "How to be The King of Airdroper",
    date: "2024-12-16",
    demoLink: "https://x.com/Autosultan_team/status/1846508068559065362",
  },
  {
    id: 1,
    name: "Arweave/AO 101",
    description: "The next Solana?",
    date: "2024-12-12",
    demoLink: "https://x.com/Autosultan_team/status/1867231906116649031",
  },
];

export const BtnList = [
  { label: "Home", link: "/", icon: "home", newTab: false },
  { label: "About", link: "/about", icon: "about", newTab: false },
  { label: "Research", link: "/research", icon: "library", newTab: false },
  { label: "Contact", link: "/contact", icon: "contact", newTab: false },
  {
    label: "Telegram 1",
    link: "https://t.me/airdropasc",
    icon: "send",
    newTab: true,
  },
  {
    label: "X",
    link: "https://x.com/Autosultan_team",
    icon: "twitter",
    newTab: true,
  },
  {
    label: "Telegram 2",
    link: "https://t.me/baelcalls",
    icon: "send",
    newTab: true,
  }, 
  {
    label: "Youtube",
    link: "https://www.youtube.com/@ZamzaSalim",
    icon: "youtube",
    newTab: true,
  },
];

export const icons = [
  { name: "binance", src: "/icons/Binance.svg", alt: "Binance" },
  { name: "okx", src: "/icons/Okx.svg", alt: "OKX" },
  { name: "mexc", src: "/icons/Mexc.svg", alt: "MEXC" },
  { name: "probit", src: "/icons/Probit.svg", alt: "Probit" },
  { name: "huobi", src: "/icons/Huobi.svg", alt: "Huobi" },
  { name: "ascendex", src: "/icons/AscendEx.svg", alt: "AscendEx" },
  { name: "bitget", src: "/icons/Bitget.svg", alt: "Bitget" },
  { name: "matrixport", src: "/icons/MatrixPort.svg", alt: "MatrixPort" },
  { name: "coinex", src: "/icons/CoinEx.png", alt: "CoinEx" },
  { name: "coin98", src: "/icons/Coin98.svg", alt: "Coin98" },
  { name: "bybit", src: "/icons/Bybit.svg", alt: "Bybit" },
  { name: "iotex", src: "/icons/Iotex.svg", alt: "Iotex" },
  { name: "zipmex", src: "/icons/Zipmex.svg", alt: "Zipmex" },
  { name: "velas", src: "/icons/Velas.svg", alt: "Velas" },
  { name: "upbit", src: "/icons/Upbit.svg", alt: "Upbit" },
  { name: "hotbit", src: "/icons/Hotbit.svg", alt: "Hotbit" },
  { name: "snapex", src: "/icons/SnapEx.png", alt: "SnapEx" },
  { name: "bingx", src: "/icons/BingX.svg", alt: "BingX" },
  { name: "bkex", src: "/icons/Bkex.svg", alt: "Bkex" },
  { name: "bitkeep", src: "/icons/Bitkeep.svg", alt: "Bitkeep" },
  { name: "bityard", src: "/icons/Bityard.svg", alt: "Bityard" },
  { name: "ten", src: "/icons/Tokenomy.svg", alt: "Tokenomy" },
  { name: "indodax", src: "/icons/Indodax.png", alt: "Indodax" },
  { name: "tokocrypto", src: "/icons/Tokocrypto.svg", alt: "Tokocrypto" },
  { name: "polkastarter", src: "/icons/PolkaStarter.svg", alt: "PolkaStarter" },
  { name: "daos", src: "/icons/daos.png", alt: "DAO Starter" },
  { name: "roseon", src: "/icons/Roseon.webp", alt: "Roseon" },
  { name: "gamestarter", src: "/icons/GameStarter.svg", alt: "GameStarter" },
  { name: "paragen", src: "/icons/Paragen.svg", alt: "Paragen" },
  { name: "vcgamers", src: "/icons/VCGamers.png", alt: "VCGamers" },
  { name: "trustfi", src: "/icons/TrustFi.png", alt: "TrustFi" },
  { name: "kommunitas", src: "/icons/Kommunitas.png", alt: "Kommunitas" },
  { name: "babylons", src: "/icons/Babylons.png", alt: "Babylons" },
  { name: "synapsenetwork", src: "/icons/Synapse.png", alt: "SynapseNetwork" },
  { name: "koistarter", src: "/icons/KoiStarter.png", alt: "KoiStarter" },
  { name: "fantomstarter", src: "/icons/FantomStarter.png", alt: "FantomStarter" },
  { name: "anonverse", src: "/icons/Anonverse.png", alt: "Anonverse" },
  { name: "safelaunch", src: "/icons/SafeLaunch.png", alt: "SafeLaunch" },
  { name: "erax", src: "/icons/Erax.svg", alt: "Erax" },
  { name: "yaygames", src: "/icons/YayGames.png", alt: "YayGames" },
  { name: "moonstarter", src: "/icons/MoonStarter.webp", alt: "MoonStarter" },
  { name: "spintop", src: "/icons/Spintop.png", alt: "Spintop" },
  { name: "karusstarter", src: "/icons/KarusStarter.png", alt: "KarusStarter" },
  { name: "bsclaunch", src: "/icons/BSCLaunch.webp", alt: "BSCLaunch" },
  { name: "palmare", src: "/icons/Palmare.png", alt: "Palmare" },
  { name: "infinitypad", src: "/icons/InfinityPad.png", alt: "InfinityPad" },
  { name: "wizardia", src: "/icons/Wizardia.png", alt: "Wizardia" },
  { name: "coinxpad", src: "/icons/Coinxpad.png", alt: "CoinxPad" },
  { name: "adroverse", src: "/icons/Adroverse.png", alt: "Adroverse" },
  { name: "evos", src: "/icons/Evos.svg", alt: "Evos E-Sport" },
  { name: "milkywayex", src: "/icons/MilkyWayEx.png", alt: "WilkyWayExchange" },
  { name: "spacemarvel", src: "/icons/SpaceMarvel.png", alt: "SpaceMarvel" },
  { name: "guildfi", src: "/icons/GuildFi.png", alt: "GuildFi" },
  // Tambahkan gambar lain di sini
];